# Name of your application. Used to uniquely configure containers.
service: personal

# # Name of the container image.
# image: bryley/homelab

# Deploy to these servers.
servers:
  web:
    - homelab: main

ssh:
  user: deployer

registry:
  server: localhost:5555

builder:
  arch: amd64

accessories:
  copyparty:
    service: copyparty
    image: copyparty/ac:1.20.13
    tags:
      - main
    proxy:
      host: copyparty.bryleybytes.com
      app_port: 3923
      healthcheck:
        path: /notes/
    files:
      - config/copyparty.conf:/cfg/copyparty.conf:ro
    directories:
      - /srv/copyparty/notes:/srv/notes:rw
      - /srv/copyparty/sessions:/srv/sessions:rw
    options:
      entrypoint: python3
    cmd: -m copyparty -c /cfg/copyparty.conf


# docker run --rm -it \
#   --name copyparty \
#   -p 3923:3923 \
#   -v "$PWD/copyparty-share:/srv/share" \
#   -v "$PWD/copyparty-config:/cfg" \
#   --entrypoint python3 \
#   copyparty/ac \
#   -m copyparty -c /cfg/copyparty.conf


  # nginx:
  #   service: nginx
  #   image: nginx:1.27.0-alpine
  #   tags:
  #     - main
  #   proxy:
  #     host: nginxtest.bryleybytes.com
  #     app_port: 80
  #     healthcheck:
  #       path: /
  #   files:
  #     - config/deploy.yml:/usr/share/nginx/html/index.html:ro
  #   directories:
  #     - nginx-data:/var/cache/nginx
