FROM fedora:latest

ENV container=docker

RUN dnf install -y sudo systemd
RUN useradd -m -s /bin/bash tester
RUN echo 'tester ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/tester

WORKDIR /workspace

STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
